const products = [
 {id:1,brand:'Samsung',name:'Galaxy S24',subtitle:'5G Smartphone',category:'Mobiles',price:74999,old:89999,rating:4.8,reviews:1284,badge:'Best seller',badgeType:'hot',image:'phone-purple.webp',visual:'visual-phone',specs:['8GB RAM','256GB','5G']},
 {id:2,brand:'Apple',name:'MacBook Air M2',subtitle:'13-inch Laptop',category:'Laptops',price:94990,old:114900,rating:4.7,reviews:963,badge:'Trending',badgeType:'',image:'laptop-silver.webp',visual:'visual-laptop',specs:['8GB RAM','256GB SSD','M2 Chip']},
 {id:3,brand:'Sony',name:'WH-CH720N',subtitle:'Wireless Headphones',category:'Audio',price:8990,old:12990,rating:4.6,reviews:742,badge:'New arrival',badgeType:'new',image:'headphones-black.webp',visual:'visual-audio',specs:['Noise cancelling','50H battery','Bluetooth 5.2']},
 {id:4,brand:'boAt',name:'Wave Call 2',subtitle:'Smart Watch',category:'Wearables',price:2499,old:3999,rating:4.4,reviews:1582,badge:'Deal',badgeType:'deal',image:'smartwatch-black.webp',visual:'visual-watch',specs:['1.83” Display','BT calling','7 days battery']},
 {id:5,brand:'ASUS',name:'ROG Performance',subtitle:'Gaming Laptop',category:'Laptops',price:82999,old:89999,rating:4.7,reviews:521,badge:'Gaming pick',badgeType:'',image:'gaming-laptop.webp',visual:'visual-gaming',specs:['16GB RAM','RTX Graphics','144Hz display']},
 {id:6,brand:'OnePlus',name:'Buds Pro',subtitle:'Wireless Earbuds',category:'Audio',price:3999,old:4999,rating:4.5,reviews:889,badge:'Popular',badgeType:'',image:'earbuds-white.webp',visual:'visual-audio',specs:['ANC','38H playback','Fast charge']},
 {id:7,brand:'Apple',name:'iPhone Premium',subtitle:'Flagship Smartphone',category:'Mobiles',price:79900,old:84900,rating:4.8,reviews:1138,badge:'Premium',badgeType:'',image:'phone-blue.webp',visual:'visual-phone',specs:['128GB','OLED display','5G ready']},
 {id:8,brand:'Sony',name:'Portable X-Bass',subtitle:'Bluetooth Speaker',category:'Audio',price:2999,old:3799,rating:4.3,reviews:617,badge:'On the go',badgeType:'',image:'speaker-black.webp',visual:'visual-audio',specs:['Deep bass','12H battery','Water resistant']},
 {id:9,brand:'Logitech',name:'G-Series Keyboard',subtitle:'RGB Gaming Keyboard',category:'Accessories',price:4599,old:5999,rating:4.6,reviews:403,badge:'Gamer choice',badgeType:'',image:'keyboard-rgb.webp',visual:'visual-accessory',specs:['RGB lighting','Mechanical feel','USB wired']},
 {id:10,brand:'Samsung',name:'Galaxy Tab',subtitle:'Everyday Tablet',category:'Tablets',price:21999,old:26999,rating:4.5,reviews:672,badge:'Great value',badgeType:'new',image:'tablet-color.webp',visual:'visual-phone',specs:['10.9” display','128GB','All-day battery']},
 {id:11,brand:'Logitech',name:'MX Anywhere',subtitle:'Wireless Mouse',category:'Accessories',price:2499,old:3299,rating:4.4,reviews:491,badge:'Work essential',badgeType:'',image:'mouse-black.webp',visual:'visual-accessory',specs:['Wireless','Multi-device','USB-C']},
 {id:12,brand:'Dell',name:'Inspiron Ultrabook',subtitle:'Slim Everyday Laptop',category:'Laptops',price:58990,old:65990,rating:4.5,reviews:356,badge:'Smart pick',badgeType:'',image:'laptop-ultrabook.webp',visual:'visual-laptop',specs:['16GB RAM','512GB SSD','Full HD']}
];
const state={category:'All',brand:'All',search:'',sort:'featured',cart:{},wishlist:new Set()};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const productImage=p=>`assets/${p.image}`;
const grid=$('#productGrid');
function renderProducts(){let list=products.filter(p=>(state.category==='All'||state.category==='Offers'||p.category===state.category)&&(state.brand==='All'||p.brand.toLowerCase()===state.brand.toLowerCase())&&(`${p.name} ${p.brand} ${p.category} ${p.subtitle}`.toLowerCase().includes(state.search.toLowerCase())));if(state.category==='Offers')list=list.filter(p=>discount(p)>=15);if(state.sort==='price-low')list.sort((a,b)=>a.price-b.price);if(state.sort==='price-high')list.sort((a,b)=>b.price-a.price);if(state.sort==='rating')list.sort((a,b)=>b.rating-a.rating);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual ${p.visual}"><span class="product-badge ${p.badgeType}">${p.badge}</span><button class="wishlist-btn ${state.wishlist.has(p.id)?'active':''}" data-wish="${p.id}" aria-label="${state.wishlist.has(p.id)?'Remove from':'Add to'} wishlist">${state.wishlist.has(p.id)?'♥':'♡'}</button><img src="${productImage(p)}" alt="${p.brand} ${p.name}" loading="lazy"></div><div class="product-info"><div class="product-brand">${p.category} · ${p.brand}</div><h3 class="product-title">${p.brand} ${p.name}</h3><div class="product-subtitle">${p.subtitle}</div><div class="rating"><span class="stars">★★★★★</span><span class="rating-number">${p.rating} (${p.reviews.toLocaleString('en-IN')})</span></div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span><span class="discount">${discount(p)}% OFF</span></div><div class="specs">${p.specs.map((s,i)=>`<span>${['▣','▤','◉'][i%3]} ${s}</span>`).join('')}</div><button class="add-cart" data-add="${p.id}">🛒 &nbsp; Add to Cart</button></div></article>`).join('');$('#emptyState').hidden=!!list.length;grid.hidden=!list.length;updateCounts();}
function discount(p){return Math.round((1-p.price/p.old)*100)}
function updateCounts(){const count=Object.values(state.cart).reduce((a,b)=>a+b,0);$('#cartCount').textContent=count;$('#drawerCount').textContent=`(${count})`;$('#wishCount').textContent=state.wishlist.size;}
function setCategory(cat){state.category=cat;state.brand='All';$$('[data-category]').forEach(b=>b.classList.toggle('selected',b.dataset.category===cat));$$('#filterTabs button').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));renderProducts();if(cat!=='All')document.querySelector('#featured').scrollIntoView({behavior:'smooth',block:'start'});}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2300)}
function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;updateCounts();renderCart();toast(`${products.find(p=>p.id===id).name} added to cart`)}
function renderCart(){const entries=Object.entries(state.cart);$('#cartItems').innerHTML=entries.length?entries.map(([id,qty])=>{const p=products.find(x=>x.id===Number(id));return `<div class="cart-item"><img src="${productImage(p)}" alt=""><div><h4>${p.brand} ${p.name}</h4><small>${p.subtitle}</small><div class="quantity-control"><button data-qty="${id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${qty}</span><button data-qty="${id}" data-delta="1" aria-label="Increase quantity">+</button><button class="remove-item" data-remove="${id}">Remove</button></div></div><div class="cart-item-price">${money(p.price*qty)}</div></div>`}).join(''):'<div class="cart-empty"><span>🛒</span><b>Your cart is waiting for something good.</b><p>Add a few favourites to get started.</p></div>';const total=entries.reduce((sum,[id,qty])=>sum+products.find(p=>p.id===Number(id)).price*qty,0);$('#cartSubtotal').textContent=money(total);$('#demoTotal').textContent=money(total);$('#checkoutBtn').disabled=!entries.length;$('#checkoutBtn').style.opacity=entries.length?'1':'.5';updateCounts()}
function openCart(){$('#overlay').classList.add('show');$('#cartDrawer').classList.add('open');document.body.style.overflow='hidden'}function closeCart(){$('#overlay').classList.remove('show');$('#cartDrawer').classList.remove('open');document.body.style.overflow=''}
function openCheckout(){if(!Object.keys(state.cart).length){toast('Your cart is empty');return}$('#checkoutModal').classList.add('open');$('#overlay').classList.add('show');$('#cartDrawer').classList.remove('open')}
function closeCheckout(){$('#checkoutModal').classList.remove('open');$('#overlay').classList.remove('show');document.body.style.overflow=''}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();state.search=$('#searchInput').value.trim();renderProducts();$('#featured').scrollIntoView({behavior:'smooth'})});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value.trim();renderProducts()});
$$('[data-category]').forEach(btn=>btn.addEventListener('click',()=>setCategory(btn.dataset.category)));
$$('[data-brand]').forEach(btn=>btn.addEventListener('click',()=>{state.brand=btn.dataset.brand;state.category='All';$$('#filterTabs button').forEach(b=>b.classList.toggle('active',b.dataset.category==='All'));renderProducts();$('#featured').scrollIntoView({behavior:'smooth'})}));
$('#filterTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-category]');if(b)setCategory(b.dataset.category)});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});grid.addEventListener('click',e=>{const add=e.target.closest('[data-add]');const wish=e.target.closest('[data-wish]');if(add)addToCart(Number(add.dataset.add));if(wish){const id=Number(wish.dataset.wish);state.wishlist.has(id)?state.wishlist.delete(id):state.wishlist.add(id);renderProducts();toast(state.wishlist.has(id)?'Added to wishlist':'Removed from wishlist')}});
$('#cartTop').addEventListener('click',()=>{renderCart();openCart()});$('#closeCart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',()=>{closeCart();closeCheckout()});$('#cartItems').addEventListener('click',e=>{const q=e.target.closest('[data-qty]');const r=e.target.closest('[data-remove]');if(q){const id=Number(q.dataset.qty);state.cart[id]=(state.cart[id]||0)+Number(q.dataset.delta);if(state.cart[id]<=0)delete state.cart[id];renderCart()}if(r){delete state.cart[Number(r.dataset.remove)];renderCart()}});$('#checkoutBtn').addEventListener('click',openCheckout);$('#closeCheckout').addEventListener('click',closeCheckout);$('#placeDemoOrder').addEventListener('click',()=>{state.cart={};renderCart();closeCheckout();closeCart();toast('Demo order placed successfully — no payment taken')});
$('#wishlistTop').addEventListener('click',()=>{state.search='';$('#searchInput').value='';state.category='All';state.brand='All';const ids=[...state.wishlist];if(!ids.length){toast('Your wishlist is empty');return}grid.innerHTML=products.filter(p=>ids.includes(p.id)).map(p=>`<article class="product-card"><div class="product-visual ${p.visual}"><span class="product-badge">Wishlist</span><button class="wishlist-btn active" data-wish="${p.id}">♥</button><img src="${productImage(p)}" alt="${p.name}"></div><div class="product-info"><div class="product-brand">${p.category} · ${p.brand}</div><h3 class="product-title">${p.brand} ${p.name}</h3><div class="product-subtitle">${p.subtitle}</div><div class="price-row"><span class="price">${money(p.price)}</span></div><button class="add-cart" data-add="${p.id}">🛒 &nbsp; Add to Cart</button></div></article>`).join('');$('#emptyState').hidden=true;grid.hidden=false;$('#featured').scrollIntoView({behavior:'smooth'});});
$('#clearFilters').addEventListener('click',()=>{state.category='All';state.brand='All';state.search='';$('#searchInput').value='';renderProducts()});$('#viewAll').addEventListener('click',()=>setCategory('All'));$('#accountBtn').addEventListener('click',()=>toast('Account sign-in is a demo feature'));
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();const email=e.currentTarget.querySelector('input').value;toast(`Thanks for subscribing, ${email}! (demo)`);e.currentTarget.reset()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeCheckout()}});
renderProducts();renderCart();
